function nv_chang_cat(a,b){nv_settimeout_disable("id_"+b+"_"+a,5E3);var c=document.getElementById("id_"+b+"_"+a).options[document.getElementById("id_"+b+"_"+a).selectedIndex].value;nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=change_cat&catid="+a+"&mod="+b+"&new_vid="+c+"&num="+nv_randomPassword(8),"","nv_chang_cat_result")}
function nv_chang_cat_result(a){a=a.split("_");a[0]!="OK"&&alert(nv_is_change_act_confirm[2]);clearTimeout(nv_timer);a=parseInt(a[1]);nv_show_list_cat(a)}function nv_show_list_cat(a){document.getElementById("module_show_list")&&nv_ajax("get",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=list_cat&parentid="+a+"&num="+nv_randomPassword(8),"module_show_list")}
function nv_del_cat(a){confirm("do you want delete?")&&nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=del_cat&catid="+a,"","nv_del_cat_result");return false}
function nv_del_cat_result(a){a=a.split("_");a[0]=="OK"?(a=parseInt(a[1]),nv_show_list_cat(a)):a[0]=="ERR"&&a[1]=="CAT"?alert(a[2]):a[0]=="ERR"&&a[1]=="ROWS"?confirm(a[4])&&nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=del_cat&catid="+a[2]+"&delallcheckss="+a[3],"edit",""):alert(nv_is_del_confirm[2]);return false}
function nv_chang_group(a,b){nv_settimeout_disable("id_"+b+"_"+a,5E3);var c=document.getElementById("id_"+b+"_"+a).options[document.getElementById("id_"+b+"_"+a).selectedIndex].value;nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=change_group&groupid="+a+"&mod="+b+"&new_vid="+c+"&num="+nv_randomPassword(8),"","nv_chang_group_result")}
function nv_chang_group_result(a){a=a.split("_");a[0]!="OK"&&alert(nv_is_change_act_confirm[2]);clearTimeout(nv_timer);a=parseInt(a[1]);nv_show_list_group(a)}function nv_show_list_group(a){document.getElementById("module_show_list")&&nv_ajax("get",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=list_group&parentid="+a+"&num="+nv_randomPassword(8),"module_show_list")}
function nv_del_group(a){confirm("Do you want delete?")&&nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=del_group&groupid="+a,"","nv_del_group_result");return false}
function nv_del_group_result(a){a=a.split("_");a[0]=="OK"?(a=parseInt(a[1]),nv_show_list_group(a)):a[0]=="ERR"&&a[1]=="CAT"?alert(a[2]):a[0]=="ERR"&&a[1]=="ROWS"?confirm(a[4])&&nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=del_group&catid="+a[2]+"&delallcheckss="+a[3],"edit",""):alert(nv_is_del_confirm[2]);return false}
function nv_chang_sources(a,b){nv_settimeout_disable("id_"+b+"_"+a,5E3);var c=document.getElementById("id_"+b+"_"+a).options[document.getElementById("id_"+b+"_"+a).selectedIndex].value;nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=change_source&sourceid="+a+"&mod="+b+"&new_vid="+c+"&num="+nv_randomPassword(8),"","nv_chang_sources_result")}
function nv_chang_sources_result(a){a.split("_")[0]!="OK"&&alert(nv_is_change_act_confirm[2]);clearTimeout(nv_timer);nv_show_list_source()}function nv_show_list_source(){document.getElementById("module_show_list")&&nv_ajax("get",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=list_source&num="+nv_randomPassword(8),"module_show_list")}
function nv_del_source(a){confirm(nv_is_del_confirm[0])&&nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=del_source&sourceid="+a,"","nv_del_source_result");return false}function nv_del_source_result(a){a=a.split("_");a[0]=="OK"?nv_show_list_source():a[0]=="ERR"?alert(a[1]):alert(nv_is_del_confirm[2]);return false}
function nv_del_block_cat(a){confirm(nv_is_del_confirm[0])&&nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=del_block_cat&bid="+a,"","nv_del_block_cat_result");return false}function nv_del_block_cat_result(a){a=a.split("_");a[0]=="OK"?nv_show_list_block_cat():a[0]=="ERR"?alert(a[1]):alert(nv_is_del_confirm[2]);return false}
function nv_chang_block_cat(a,b){nv_settimeout_disable("id_"+b+"_"+a,5E3);var c=document.getElementById("id_"+b+"_"+a).options[document.getElementById("id_"+b+"_"+a).selectedIndex].value;nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=chang_block_cat&bid="+a+"&mod="+b+"&new_vid="+c+"&num="+nv_randomPassword(8),"","nv_chang_block_cat_result")}
function nv_chang_block_cat_result(a){a.split("_")[0]!="OK"&&alert(nv_is_change_act_confirm[2]);clearTimeout(nv_timer);nv_show_list_block_cat()}function nv_show_list_block_cat(){document.getElementById("module_show_list")&&nv_ajax("get",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=list_block_cat&num="+nv_randomPassword(8),"module_show_list")}
function nv_chang_block(a,b,c){nv_settimeout_disable("id_weight_"+b,5E3);var d=document.getElementById("id_weight_"+b).options[document.getElementById("id_weight_"+b).selectedIndex].value;nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=change_block&id="+b+"&bid="+a+"&&mod="+c+"&new_vid="+d+"&num="+nv_randomPassword(8),"","nv_chang_block_result")}
function nv_chang_block_result(a){a=a.split("_");a[0]!="OK"&&alert(nv_is_change_act_confirm[2]);a=parseInt(a[1]);nv_show_list_block(a)}function nv_show_list_block(a){document.getElementById("module_show_list")&&nv_ajax("get",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=list_block&bid="+a+"&num="+nv_randomPassword(8),"module_show_list")}
function nv_del_block_list(a,b){for(var c="",d=a["idcheck[]"],e=0;e<d.length;e++)d[e].checked&&(c=c+","+d[e].value);c!=""&&nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=change_block&del_list="+c+"&bid="+b+"&num="+nv_randomPassword(8),"","nv_chang_block_result")}
function nv_main_action(a,b,c){for(var d=a["idcheck[]"],a="",e=0;e<d.length;e++)d[e].checked&&(a=a+d[e].value+",");if(a!="")if(c=document.getElementById("action").value,c=="delete")confirm(nv_is_del_confirm[0])&&nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=del_content&listid="+a+"&checkss="+b,"","nv_del_content_result");else if(c=="addtoblock")window.location.href=script_name+"?"+nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=block&listid="+a+"#add";else if(c=="publtime")window.location.href=script_name+"?"+nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=publtime&listid="+a+"&checkss="+b;else{if(c=="exptime")window.location.href=script_name+"?"+nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=exptime&listid="+a+"&checkss="+b}else alert(c)}
function nv_del_content(a,b){confirm(nv_is_del_confirm[0])&&nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=del_content&id="+a+"&checkss="+b,"","nv_del_content_result");return false}function nv_check_movecat(a,b){if(a.catidnews.value==0)return alert(b),false}
function nv_del_content_result(a){a=a.split("_");a[0]=="OK"?window.location.href=script_name+"?"+nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=items":a[0]=="ERR"?alert(a[1]):alert(nv_is_del_confirm[2]);return false}
function create_keywords(){var a=strip_tags(document.getElementById("keywords").value);a!=""&&nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=keywords&content="+encodeURIComponent(a),"","res_keywords");return false}function res_keywords(a){a!="n/a"?document.getElementById("keywords").value=a:document.getElementById("keywords").value="";return false}
function nv_sh(a,b){document.getElementById(a).options[document.getElementById(a).selectedIndex].value==3?nv_show_hidden(b,1):nv_show_hidden(b,0);return false}function findValue(a){return a==null?alert("No match!"):a.extra?a.extra[0]:a.selectValue}function selectItem(a){sValue=findValue(a)}function formatItem(a){return a[0]+" ("+a[1]+")"}function nv_chang_pays(a,b,c,d){b=$(b).val();$.ajax({type:"POST",url:c,data:"oid="+a+"&w="+b,success:function(){window.location=d}})}
function ChangeActive(a,b){var c=$(a).attr("id");$.ajax({type:"POST",url:b,data:"id="+c,success:function(a){alert(a)}})}function get_alias(){var a=strip_tags(document.getElementById("idtitle").value);a!=""&&nv_ajax("post",script_name,nv_name_variable+"="+nv_module_name+"&"+nv_name_variable+"="+nv_module_name+"&"+nv_fc_variable+"=alias&title="+encodeURIComponent(a),"","res_get_alias");return false}
function res_get_alias(a){a!=""?document.getElementById("idalias").value=a:document.getElementById("idalias").value="";return false};